### ISSUE TITLE
FAQ panel

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/ddk-map#26]
Implement FAQ panel

![image.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/b5234ff3-e55f-4d31-ad43-f3bdab59635f)

**Comment by lougroshek** [comment]
We have no copy for faq panel

**Comment by laurendoone** [comment]
@lougroshek noted, we'll ask the client to write copy for this. On a somewhat related note, James would like the client to be able to edit this FAQ copy on their own, but not sure what the best method would be... do you have any recommendations? On the SEDA site, there was the [Explorer Language Sheet ](https://docs.google.com/spreadsheets/d/1L633lO5wfQGLbaVnaSnIg9TrprX9k4Ie8qe_CLDmQN8/edit#gid=0 )where the client can edit the FAQ questions/answers and it updates on the site with each build. Should we do something like that for this project?

**Comment by lougroshek** [comment]
[Language pack inheritance](https://github.com/Hyperobjekt/untd-site/blob/920106fc796f0a02bc1156735077f3af3b7c1080/src/pages/explorer.js#L56) from the shell site has been in place since I created these repos.

**Comment by laurendoone** [comment]
@lougroshek what does that do? 😬

**Comment by lougroshek** [comment]
@laurendoone It does this:
> On a somewhat related note, James would like the client to be able to edit this FAQ copy on their own, but not sure what the best method would be... do you have any recommendations? On the SEDA site, there was the Explorer Language Sheet where the client can edit the FAQ questions/answers and it updates on the site with each build. Should we do something like that for this project?

**Comment by lougroshek** [comment]
Sorry, I'm getting about 20 of these notifications a day. I thought this
was for untd-map. We don't have any cms in place for this project because
the client told us they didn't need one. If they need a cms that would be
additional time.

**Comment by lougroshek** [comment]
@laurendoone Do we have content for this faq panel?
